### ISSUE TITLE
CRA 5 (Webpack 5) strange behaviour

### ISSUE THREAD

**Issue by bdecarne** [tommie-lie/cra-antd-customization#1]
Thank you for this nice solution, I love it.

I tried to make it work with CRA 5, but it didn't work... until I rename the less file to match `scss` or `css` extension !

```javascript
// DO NOT WORK :

// eslint-disable-next-line import/no-webpack-loader-syntax
import './antd.less.css!=!less-loader?{"lessOptions":{"javascriptEnabled":true}}!./antd.less';

// WORK :

// eslint-disable-next-line import/no-webpack-loader-syntax
import './antd.scss.css!=!less-loader?{"lessOptions":{"javascriptEnabled":true}}!./antd.scss';

// or

// eslint-disable-next-line import/no-webpack-loader-syntax
import './antd.css.css!=!less-loader?{"lessOptions":{"javascriptEnabled":true}}!./antd.css';
```

Do you have an idea to explain this ?

**Comment by tommie-lie** [comment]
Thanks, I also spent last weekend figuring this out an then got sidetracked by Tailwind 3.0, which also interferes with antd.

I think this has something to do with how Webpack 5 handles [assets](https://webpack.js.org/guides/asset-management/). It seems that the "regular" processing of files now only works when the file matches a certain regex. I am not a webpack expert so I don't know what we can do with cra's webpack config, so if you find another trick instead of renaming to `.css`, any help is welcome: https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/webpack.config.js#L349

**Comment by bdecarne** [comment]
My investigations leads me the same conclusion : when i add `less` to the excluded patterns here https://github.com/facebook/create-react-app/blob/a422bf227cf5294a34d68696664e9568a152fd8f/packages/react-scripts/config/webpack.config.js#L595 its works well.

Fun fact : my stack also include tailwind 3.0 and i saw some glitches with antd, specialy with icons. I need to take some time to investigate...

**Comment by tommie-lie** [comment]
@bdecarne re:tailwind: I'm not sure we're talking about the same issue, but we also had issues with icons and this fixed it for us:
```
.anticon svg {
  vertical-align: initial;
}
```

About the webpack issue, the closest I can get is 
```javascript
import bar from 'antd-overrides.css.webpack[asset/resource]!=!less-loader?{\"lessOptions\":{\"javascriptEnabled\":true}}!./antd-overrides.less'
```
where `bar` now is a string that contains a URL that the dev server resolves to the processed CSS. I **could** insert a `<link rel="stylesheet">` using this URL at runtime, but I haven't given up on a better solution yet...
It's too late to continue working on this tonight, though, I have to get some sleep.

**Comment by tommie-lie** [comment]
After hours after hours of debugging webpack's loader mechanism and the loaders themselves, I finally found another solution:
The culprit is how webpack handles imports generated by the style-loader. The `!=!` import from our own .js file is replaced with some other JavaScript that has an actual `import` statement with the `!=!` syntax replaced with the loader chain for css files. So far, so good. But this import statement ends with ".less", which is then matched against the `webpack.config.js` of cra to be of type `asset/resource`. So the style-loader cannot get the actual styles, but only receives the filename, which it does not correctly understand. I'm not sure if this is a problem in webpack or in style-loader (any help to file a correct bug (or fix it) is welcome!), but a workaround is this:

`App.js:`
```
import "./antd-with-overrides.css";
```

`antd-with-overrides.css:`
```
@import "foo.css!=!less-loader?{\"lessOptions\":{\"javascriptEnabled\":true}}!antd-overrides.less";
```

`antd-overrides.less:`
```
@import "~antd/lib/style/themes/default.less";
@import "~antd/dist/antd.less";

@primary-color: #88dbad;
@border-radius-base: 10px;
```

Note the indirection of having the less-loader **imported from a CSS file** and having that CSS file imported in your app.


I will update the howto and repository accordingly in the next days.

**Comment by tommie-lie** [comment]
I updated the guide, let me know if something is not working.
